// src/main/resources/hilla/testing/frontend/lit/users-page.ts
import { html, nothing } from 'lit';
import { customElement } from 'lit/decorators.js';
import { repeat } from 'lit/directives/repeat.js';
import { View } from '../../views/view.js';
import * as UsersEndpoint from 'Frontend/generated/UsersEndpoint.js';
import User from 'Frontend/generated/com/vaadin/demo/hilla/testing/User.js';

@customElement('users-page')
export default class UsersPage extends View {
  #users: readonly User[] = [];

  async connectedCallback() {
    super.connectedCallback();
    this.#users = await UsersEndpoint.findAll();
  }

  render() {
    return html`
      <table data-testid="users">
        <th>
          <td>First Name</td>
          <td>Last Name</td>
        </th>
        ${repeat(
          this.#users,
          ({ id }) => id,
          ({ firstName, lastName }) => html`<tr>
            <td>${firstName}</td>
            <td>${lastName}</td>
          </tr>`
        )}
      </table>
    `;
  }
}

// src/main/resources/hilla/testing/frontend/react/UsersPage.tsx
import { useEffect, useState } from 'react';
import * as UsersEndpoint from 'Frontend/generated/UsersEndpoint.js';
import User from 'Frontend/generated/com/vaadin/demo/hilla/testing/User.js';

export default function UsersPage() {
  const [users, setUsers] = useState<readonly User[]>([]);

  useEffect(() => {
    UsersEndpoint.findAll().then((result) => setUsers(result));
  }, []);

  return (
    <table data-testid="users">
      <th>
        <td>First Name</td>
        <td>Last Name</td>
      </th>
      {users.map(({ id, firstName, lastName }) => (
        <tr key={id}>
          <td>{firstName}</td>
          <td>{lastName}</td>
        </tr>
      ))}
    </table>
  );
}
